### ISSUE TITLE
Please add uci hash option

### ISSUE THREAD

**Issue by rwbc** [cosmobobak/virtue#5]
Current versions always use around 512MB. It would be nice if the user can set the hash size to lower values for fast games,
w/o recompiling for a different size.

Thanks!

Guenther (RWBC)

**Comment by SzotsGabor** [comment]
+1

**Comment by cosmobobak** [comment]
sure! i'll try to get a 2.4.1 version out by tomorrow, and that should have hash uci options

**Comment by cosmobobak** [comment]
okay, 2.4.1 is out, changing hash size should work!

**Comment by rwbc** [comment]
Thanks! It seems to work _almost_. I noticed though something from cmd.
(at least here on my old WIN7 quadcore)

If I set hash from cmd it only increases the hash size, but never decreases it.
I checked quickly with SF and actually it immediately changes the hash size
in all directions as expected.

**Description (test case):**
(also tested with ucinewgame and isready commands inbetween)

This does not work vor Viridithas II it will remain at the value 128 and only
change if a higher value is given later later from cmd
```
setoption name Hash value 128
setoption name Hash value 32
```
This works
```
setoption name Hash value 64
setoption name Hash value 1024
```

I guess for most user cases it is not so important, but there might be a problem
when using some cmd tools with it or a GUI which doesn't reload the engine
for a new game/match or whatever with a new setting.

**Comment by SzotsGabor** [comment]
What other changes have you made to v2.4.0? Do they impact playing strength? This is important to me because I am already running a test gauntlet for the CCRL blitz list and I would not want to repeat games.
FYI, I have compiled the source, with the hash set to 256 MB and that is what I am using. The changes I made were BTW, the source is still at 2.3.0.
These are the changes I made to the source:
pub const MEDIUM_TABLE_SIZE: usize = MEGABYTE * 256 / TT_ENTRY_SIZE;
pub const DEFAULT_TABLE_SIZE: usize = MEDIUM_TABLE_SIZE;
I hope I haven't spoiled anything.

**Comment by cosmobobak** [comment]
@rwbc i don't know why it doesn't reduce hash size, it really should, i'll try to figure that out.
@SzotsGabor 2.3 -> 2.4 is a very big difference, i've added kingsafety and a bunch of other stuff, but 2.4.1 has only one little tweak to search and i haven't seen elo to have actually changed measurably between 2.4.0 and 2.4.1. Your approach to hard-coding hashtable size should work, and i'm alright with you using it.

**Comment by cosmobobak** [comment]
@rwbc ah! i've figured it out - the way my hashtable resizes doesn't reduce the used memory, but does reduce the hashtable accessible to the program, due to the behaviour of `Vec::truncate`
![image](https://user-images.githubusercontent.com/56003038/183675273-592911d0-2ab4-4ed7-b113-e97f822354bb.png)
("this method has no effect on the allocated capacity of the vector")
This means that viridithas isn't "cheating" by using a hashtable larger that he has been given, but it is annoying that he won't let go of the memory. I'll fix this today.

**Comment by rwbc** [comment]
Great! Thanks for the quick fix. I can confirm that the behaviour is correct now.
You can close this issue :)
